server:
  port: 10080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eagle.base

spring:
  profiles:
    active: dev


ai:
  api:
    key: NONE
    photo:
      post: https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis
      get: https://dashscope.aliyuncs.com/api/v1/tasks/{TASK_ID}
    text:
      post: https://dashscope.aliyuncs.com/compatible-mode/v1