version: '3'
services:
  eagle-mysql:
    container_name: eagle_mysql
    image: mysql:8.0
    volumes:
      - ./generated.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=MysqlRoot=root
# default: close port 3306
#    ports:
#      - "3306:3306"
    restart: on-failure

  eagle-app:
    container_name: eagle_app
    image: openjdk:8-jdk-alpine
    volumes:
      - ../eagle-all/target/eagle-all.jar:/app/eagle-all.jar  # 将本地的 app 目录挂载到容器中的 /app 目录
      - ./hot-news:/app/hot-news
#    ports:
#      - "10080:10080"  # 映射容器的 10080 端口到宿主机的 10080 端口
    env_file:
      - ./API_KEY.env
    command:
      - "nohup"
      - "java"
      - "-jar"
      - "/app/eagle-all.jar"
      - "--spring.profiles.active=prod"
      - ">/app/log.log"
      - "&"
    restart: on-failure
  eagle-nginx:
    container_name: eagle_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./hot-news:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always