version: '3'
services:
  eagle-mysql:
    container_name: eagle-mysql
    image: mysql:8.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=MysqlRoot=root
    ports:
      - "3306:3306"
