apiVersion: v1
kind: Service
metadata:
  name: eagle-web-ingress-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: eagle-web-app
  ports:
    - port: 8080
      targetPort: {{ .Values.service.targetPort }}
      nodePort: 30085
  type: LoadBalancer